Modifications to generic fMRIVolume and fMRISurface pipelines to run on longitudinal sessions.
Washington-University/HCPpipelines pull request #319
Opened 2024-12-29 00:12 UTC by mmilch01

This pull request comprises modifications to generic fMRIVolume and fMRISurface to run on longitudinal timepoints. Prerequisites for GenericfMRIVolumeProcessingPipeline are:
1. All cross-sectional pipelines must have been run up to post-Freesurfer for all timepoints.
2. All longitudinal pipelines for the corresponding timepoints must have been run up to post-Freesurfer.
3.  GenericfMRIVolumeProcessingPipeline must have been run on all cross-sectional pipelines.
4. All timepoints must be under the same processing directory.

Prerequisites for fMRISurface are the same plus GenericfMRIVolumeProcessingPipeline must have been run on all longitudinal timepoints.

2024-12-30 09:42 UTC, demsarjure commented
@mmilch01 

1. I assume that in 
```
Prerequisites for fMRISurface are the same plus GenericfMRIVolumeProcessingPipeline must have been run on all longitudinal timepoints.
```
`GenericfMRIVolumeProcessingPipeline ` should be `GenericfMRISurfaceProcessingPipeline`?


2. It would be probably great, if I ran some tests for this on our end. Misha, can you please paste 2 example calls that you used for tests on your end, one for long volume and one for long surface. Just so I have something to quickly compare my command calls with. Thanks!

2024-12-30 09:50 UTC, demsarjure commented
It looks like this MR now includes changes from Volume + Surface and also changes from the long FS which were already merged into master? So the review tab shows a lot of code that is already tested and reviewed. Maybe it would be best to have a new branch for the new stuff?

Also, the branch is not in sync with the current master, so it would be best to merge the current master into this and resolve the conflicts. Or the cleanest way, which is to create new branch of the master and apply only long volume and long surface changes to it.

2024-12-30 09:54 UTC, demsarjure reviewed
I did a somewhat quick review and things look good. As usual I might report some bugs later on, when I actually start running tests.

2024-12-30 09:54 UTC, demsarjure commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline-0.sh
What is the `-0` suffix in `GenericfMRIVolumeProcessingPipeline-0.sh`?

2024-12-30 09:54 UTC, demsarjure commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ $DoSliceTimeCorrection = "TRUE" ] ; then
Weird offset at the beginning of this line.

2024-12-30 21:54 UTC, coalsont commented
> It looks like this MR now includes changes from Volume + Surface and also changes from the long FS which were already merged into master? So the review tab shows a lot of code that is already tested and reviewed. Maybe it would be best to have a new branch for the new stuff?
> 
> Also, the branch is not in sync with the current master, so it would be best to merge the current master into this and resolve the conflicts. Or the cleanest way, which is to create new branch of the master and apply only long volume and long surface changes to it.

Rebase is a cleaner way to resolve normal conflicts (this situation isn't normal).  Merge commits are weird and awkward, and hard to look at diffs of.  "In sync" isn't really applicable here, the whole purpose of a PR is to propose changes, conflicts mean that someone else has also made changes to the same files (or, it can be a symptom that your branch's starting point is wrong or contains extra stuff).

I can try to salvage the intended commits.

2024-12-31 15:09 UTC, mmilch01 commented
> 1. I assume that in
> 
> ```
> Prerequisites for fMRISurface are the same plus GenericfMRIVolumeProcessingPipeline must have been run on all longitudinal timepoints.
> ```
> 
> `GenericfMRIVolumeProcessingPipeline ` should be `GenericfMRISurfaceProcessingPipeline`?
> 
Longitudinal fMRISurface needs longitudinal fMRIVolume to have been run on the same timepoint. Cross-sectional fMRISurface is not required to have been run. 

> 2. It would be probably great, if I ran some tests for this on our end. Misha, can you please paste 2 example calls that you used for tests on your end, one for long volume and one for long surface. Just so I have something to quickly compare my command calls with. Thanks!

I'll post my example batch scripts on Slack shortly.

2024-12-31 15:10 UTC, mmilch01 commented
> It looks like this MR now includes changes from Volume + Surface and also changes from the long FS which were already merged into master? So the review tab shows a lot of code that is already tested and reviewed. Maybe it would be best to have a new branch for the new stuff?
> 
> Also, the branch is not in sync with the current master, so it would be best to merge the current master into this and resolve the conflicts. Or the cleanest way, which is to create new branch of the master and apply only long volume and long surface changes to it.

This should have been fixed now.

2024-12-31 15:12 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline-0.sh
> What is the `-0` suffix in `GenericfMRIVolumeProcessingPipeline-0.sh`?
That's a backup file that somehow made it into one of commits. should be fixed now.

2025-01-03 23:31 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +opts_AddOptional '--output-native' 'OutputNative' 'binary' "Flag to output in native T1w space [no by default]" "0"
This doesn't seem to be implemented.

"binary" and "flag" don't seem like explanations that would be obvious to users.  I typically use `'TRUE or FALSE'` or `'YES or NO'` for these, and try to be consistent within a script.

2025-01-03 23:43 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +	fi
```suggestion
    cp -rf "$ResultsFolder" "$ResultsFolderLong"
    fMRIFolderLong="$Path"/"$SessionLong"/"$NameOffMRI"
    cp -rf "$fMRIFolder" "$fMRIFolderLong"
```
Under `set -eu` and `debug.shlib`, all nonzero exit statuses will be caught before they reach your conditionals.  If you really feel these custom messages are necessary, you would need to do it this way:

```
    if ! cp -rf "$ResultsFolder" "$ResultsFolderLong"
    then
        log_Err_Abort "Copying cross-sectional output $ResultsFolder to longitudinal session folder $ResultsFolderLong failed."
    fi
```

You need whitespace on both sides of the `!`, due to bash history syntax also using that symbol.

The second conditional also somehow ended up with tabs instead of spaces.

2025-01-03 23:49 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"
Why does this no longer contain "_orig_"?

2025-01-05 02:51 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +opts_AddOptional '--output-native' 'OutputNative' 'binary' "Flag to output in native T1w space [no by default]" "0"
Let's move the physical space output stuff to a separate pull request.

2025-01-05 03:21 UTC, glasserm commented on fMRISurface/scripts/GenerateFMRIScenes.sh
> +opts_AddMandatory '--session' 'Session' 'Session ID' "Session"
Should the last session be Subject for backwards compatibility?

2025-01-05 03:25 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ -n "$fMRIReference" ] && [ "$fMRIReference" != "NONE" ]; then
@demsarjure @sivcek We don't know how the fMRIReference works. Can you assist with ensuring that that functionality works with longitudinal mode?  Perhaps it is relevant only to cross-sectional processing and can be ignored?

2025-01-05 03:34 UTC, glasserm commented on fMRIVolume/scripts/OneStepResampling.sh
>  opts_AddMandatory '--ojacobian' 'JacobianOut' 'image' "output transformed + distortion corrected Jacobian image"
This seems to have a lot of native space changes in it that should be in another pull request.

2025-01-05 03:36 UTC, glasserm commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #TODO: correctly point to longitudinal output image
Is this still at TODO?

2025-01-05 03:37 UTC, glasserm commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #TODO: correctly point to longitudinal output
Is this still a TODO?

2025-01-05 03:37 UTC, glasserm commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +        #TODO: correctly point to longitudinal output
Is this still at TODO?

2025-01-05 03:37 UTC, glasserm commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #TODO: correctly point to longitudinal output
Is this still a TODO?

2025-01-05 03:46 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +#Split echos.
Only run in cross-sectional.

2025-01-05 03:47 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    cmd=(${RUN} ${PipelineScripts}/OneStepResampling.sh \
Why do we have this cmd here?

2025-01-05 03:48 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +        else #never triggered in Longitudinal mode
@demsarjure @sivcek This needs your attention.

2025-01-05 03:53 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"
Also need @demsarjure @sivcek to review.

2025-01-05 03:56 UTC, glasserm requested changes
I have made various comments.  Please address them and also @demsarjure @sivcek please assist with the fMRIReference stuff. Thanks!

2025-01-05 09:05 UTC, demsarjure commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"
@glasserm I already went over the code and provided some comments. I will probably have some more comments/issues to report once I start testing. If all goes to plan, should be sometime this week.

2025-01-05 09:06 UTC, demsarjure commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ -n "$fMRIReference" ] && [ "$fMRIReference" != "NONE" ]; then
Yes, I believe fMRIReference is irrelevant for longitudinal processing.

2025-01-05 09:07 UTC, demsarjure commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +        else #never triggered in Longitudinal mode
Like mentioned above, I think this is fine as reference is not needed any more in longitudinal processing.

2025-01-05 14:39 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ -n "$fMRIReference" ] && [ "$fMRIReference" != "NONE" ]; then
In that case we don't need to have an error message here if this code won't run anyway in longitudinal mode.

2025-01-06 15:20 UTC, mmilch01 commented on fMRISurface/scripts/GenerateFMRIScenes.sh
> +opts_AddMandatory '--session' 'Session' 'Session ID' "Session"
Yes. Fixed.

2025-01-06 15:23 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +opts_AddOptional '--output-native' 'OutputNative' 'binary' "Flag to output in native T1w space [no by default]" "0"
Ok

2025-01-06 15:30 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +	fi
Ok

2025-01-06 15:32 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ $DoSliceTimeCorrection = "TRUE" ] ; then
I think it is fixed in the current version.

2025-01-06 16:17 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"
Diff here is extremely confusing. Longitudinal related changes are actually quite minimal and local. It may be best to compare these files side by side.

2025-01-06 16:18 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +#Split echos.
Sorry, could you expand on what you mean?

2025-01-06 16:19 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    cmd=(${RUN} ${PipelineScripts}/OneStepResampling.sh \
I used it for debugging. Reverse?

2025-01-06 16:37 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #TODO: correctly point to longitudinal output image
Reference need not change for longitudinal, as long as image space does not change between timepoints. As far as I know, HCP pipelines don't support varying timepoint resolution? Or should we?

2025-01-06 16:37 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #TODO: correctly point to longitudinal output
See above

2025-01-06 16:37 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +        #TODO: correctly point to longitudinal output
See above

2025-01-06 16:45 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #TODO: correctly point to longitudinal output
See above

2025-01-06 16:50 UTC, mmilch01 commented on fMRIVolume/scripts/OneStepResampling.sh
>  opts_AddMandatory '--ojacobian' 'JacobianOut' 'image' "output transformed + distortion corrected Jacobian image"
All space change code is commented out.

2025-01-06 17:42 UTC, glasserm commented
The fMRIReference code should not actually do anything in longitudinal mode if longitudinal mode is implemented correctly, so we don't need an error message here.

Matt.
________________________________
From: mmilch01 ***@***.***>
Sent: Monday, January 6, 2025 9:27 AM
To: Washington-University/HCPpipelines ***@***.***>
Cc: Glasser, Matthew ***@***.***>; Mention ***@***.***>
Subject: Re: [Washington-University/HCPpipelines] Modifications to generic fMRIVolume and fMRISurface pipelines to run on longitudinal sessions. (PR #319)


* External Email - Caution *

@mmilch01 commented on this pull request.

________________________________

In fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904292194>:

> @@ -428,6 +435,21 @@ then
     log_Err_Abort "the --usejacobian option must be 'true' or 'false'"
 fi

+IsLongitudinal=$(opts_StringToBool "$IsLongitudinal")
+T1wCross2LongXfm="NONE"
+
+if (( IsLongitudinal )); then
+    if [ ! -d "$Path/$SessionLong" ]; then
+        log_Err_Abort "the --longitudinal-session must be specified and folder must exist in longitudinal mode"
+    fi
+    T1wCross2LongXfm=$Path/$SessionLong/T1w/xfms/T1w_cross_to_T1w_long.mat
+    if [ ! -f "$T1wCross2LongXfm" ]; then
+        log_Err_Abort "Longitudinal session $SessionLong: cross-sectional to longitudinal transform $T1wCross2LongXfm does not exist. Has longtudinal PostFreesurfer been run?"
+    fi
+    if [ -n "$fMRIReference" ] && [ "$fMRIReference" != "NONE" ]; then


I would leave this error message to educate users in case they try to use fMRIReference in longitudinal mode.

—
Reply to this email directly, view it on GitHub<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904292194>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AALSNTBWG2F7W52555ZRK7T2JKOFZAVCNFSM6AAAAABUKHZF5OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMZSGM4DKMZVG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

2025-01-06 17:43 UTC, glasserm commented
You should not run this block in longitudinal mode, so please if/then it accordingly.

Matt.


***@***.***?anonymous&ep=bwmEmailSignature>                Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________
From: mmilch01 ***@***.***>
Sent: Monday, January 6, 2025 10:19 AM
To: Washington-University/HCPpipelines ***@***.***>
Cc: Glasser, Matthew ***@***.***>; Mention ***@***.***>
Subject: Re: [Washington-University/HCPpipelines] Modifications to generic fMRIVolume and fMRISurface pipelines to run on longitudinal sessions. (PR #319)


* External Email - Caution *

@mmilch01 commented on this pull request.

________________________________

In fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904354795>:

>
-#Split echos
+#Split echos.


Sorry, could you expand on what you mean?

—
Reply to this email directly, view it on GitHub<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904354795>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AALSNTDW7OJ722KTGMQT3DT2JKUHNAVCNFSM6AAAAABUKHZF5OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMZSGQ4TCNRYGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

2025-01-06 17:44 UTC, glasserm commented
You need to suppress white space changes and then it is not confusing.  I always forget to do that too.

Matt.
________________________________
From: mmilch01 ***@***.***>
Sent: Monday, January 6, 2025 10:17 AM
To: Washington-University/HCPpipelines ***@***.***>
Cc: Glasser, Matthew ***@***.***>; Mention ***@***.***>
Subject: Re: [Washington-University/HCPpipelines] Modifications to generic fMRIVolume and fMRISurface pipelines to run on longitudinal sessions. (PR #319)


* External Email - Caution *

@mmilch01 commented on this pull request.

________________________________

In fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904352827>:

>
-    log_Msg "$fMRIFolder/$OrigTCSName: xorient=${xorient}, yorient=${yorient}, zorient=${zorient}"
+        for simage in SBRef_nonlin SBRef_nonlin_norm
+        do
+            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"


Diff here is extremely confusing. Longitudinal related changes are actually quite minimal and local. It may be best to compare these files side by side.

—
Reply to this email directly, view it on GitHub<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904352827>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AALSNTBFQIZWI25FFMA5DDT2JKUCDAVCNFSM6AAAAABUKHZF5OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMZSGQ4DQNZZGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

2025-01-06 17:45 UTC, glasserm commented
Yes if we don't need it.

Matt.
________________________________
From: mmilch01 ***@***.***>
Sent: Monday, January 6, 2025 10:20 AM
To: Washington-University/HCPpipelines ***@***.***>
Cc: Glasser, Matthew ***@***.***>; Mention ***@***.***>
Subject: Re: [Washington-University/HCPpipelines] Modifications to generic fMRIVolume and fMRISurface pipelines to run on longitudinal sessions. (PR #319)


* External Email - Caution *

@mmilch01 commented on this pull request.

________________________________

In fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904356000>:

> @@ -872,7 +939,7 @@ log_Msg "mkdir -p ${fMRIFolder}/OneStepResampling"
 mkdir -p ${fMRIFolder}/OneStepResampling
 tscArgs="";sctArgs="";
 for iEcho in $(seq 0 $((nEcho-1))) ; do
-    ${RUN} ${PipelineScripts}/OneStepResampling.sh \
+    cmd=(${RUN} ${PipelineScripts}/OneStepResampling.sh \


I used it for debugging. Reverse?

—
Reply to this email directly, view it on GitHub<https://github.com/Washington-University/HCPpipelines/pull/319#discussion_r1904356000>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AALSNTG3EFTRQY37R5NNZPD2JKULNAVCNFSM6AAAAABUKHZF5OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMZSGQ4TGNZQHA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.

2025-01-06 20:25 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    cmd=(${RUN} ${PipelineScripts}/OneStepResampling.sh \
He is using it to print the full sub-script command before running it (without writing it twice).  `newopts` automatically logs its arguments (in `OneStepResampling`), though.

2025-01-06 20:32 UTC, coalsont commented on fMRISurface/GenericfMRISurfaceProcessingPipeline.sh
> +opts_AddMandatory '--session' 'Session' 'session ID' "--subject"
This is missing a long description, so the intention of `--subject` to be a legacy flag will not currently work (wrong number of arguments).  Use a quoted empty string, if nothing else.
```suggestion
opts_AddMandatory '--session' 'Session' 'session ID' "" '--subject'
```

2025-01-06 20:34 UTC, coalsont commented on fMRISurface/GenericfMRISurfaceProcessingPipeline.sh
> +    log_Warn "         HCP Pipelines as it results in poorer cross-session functional and cortical areal "
This probably shouldn't have been find/replaced here.

2025-01-06 20:39 UTC, coalsont commented on fMRISurface/scripts/RibbonVolumeToSurfaceMapping.sh
> +Session="$3"
When the internal logic of a script doesn't need to change, I'm not sure we need to go to the trouble of replacing the variable names.  I'm not saying undo this, but maybe don't do it for future scripts that don't have functionality changes.

2025-01-06 20:41 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +opts_AddMandatory '--session' 'Session' 'Session ID' "--subject"
Again, missing a long description argument, so it will not use the `--subject` argument as a legacy flag.

2025-01-06 20:50 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ -n "$fMRIReference" ] && [ "$fMRIReference" != "NONE" ]; then
It sounds like "not supported" is not the correct thing to tell users, it is more like "fmri reference is used during the initial cross-sectional run on a timepoint, but ignored during the subsequent longitudinal call on the same timepoint".  That suggests it should be a warning, not an error.

If this is how longitudinal is intended to be run (first with `--is-longitudinal=FALSE`, then later with `--is-longitudinal=TRUE` on the same session+fMRIName pair), then perhaps this should be explained in the usage somewhere (or users will think "yes, I collected longitudinal data, so I just run it once with `TRUE`, right?").

2025-01-06 20:53 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +        log_Err_Abort "the --longitudinal-session must be specified and folder must exist in longitudinal mode"
This suggests `--longitudinal-session` must be specified and non-empty whenever `--is-longitudinal=TRUE`.  So, do we really even need the `--is-longitudinal` option, or should it simply test if `--longitudinal-session` gave an empty string?

2025-01-06 21:01 UTC, coalsont commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +        log_Err_Abort "--t1w-cross2long-xfm must point to a valid file when --is-longitudinal is used"
It could be argued that `--is-longitudinal` is redundant here also (you wouldn't supply `--t1w-cross2long-xfm` in cross-sectional mode).

2025-01-06 21:14 UTC, coalsont commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            if [[ X$(echo "if ( (${MagnitudeBrainSize} / ${T1wBrainSize}) > 1.25 ) {1}" | bc -l) = X1 || X$(echo "if ( (${MagnitudeBrainSize} / ${T1wBrainSize}) < 0.75 ) {1}" | bc -l) = X1 ]] ; then
```suggestion
            if [[ "$(echo "((${MagnitudeBrainSize} / ${T1wBrainSize}) > 1.25) || ((${MagnitudeBrainSize} / ${T1wBrainSize}) < 0.75)" | bc -l)" == 1 ]] ; then
```
As long as we are editing this line, the `X$something` construction isn't needed with `[[` (or simply with proper quoting).  `bc` can do logical or, instead of two separate conditionals (and without needing conditionals inside bc at all).

2025-01-06 21:19 UTC, coalsont commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #ScoutExtension="_undistorted" this is now initialized before case switch to accomodate longitudinal mode
I would just delete these lines rather than commenting them out.

2025-01-06 21:22 UTC, coalsont commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> -        cp "${WD}/${ScoutInputFile}${ScoutExtension}2T1w_init.mat" "${WD}/fMRI2str.mat"
Deleting the copy command but not the comments is confusing.

2025-01-06 21:46 UTC, coalsont commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> -        cp "${WD}/${ScoutInputFile}${ScoutExtension}2T1w_init.mat" "${WD}/fMRI2str.mat"
To be clear: there is a copy of just the comments on (currently) line 473.  Due whitespace changes, the edits tagged by my comment show them as being deleted, when they still exist in the file.

2025-01-07 01:31 UTC, glasserm commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            if [[ X$(echo "if ( (${MagnitudeBrainSize} / ${T1wBrainSize}) > 1.25 ) {1}" | bc -l) = X1 || X$(echo "if ( (${MagnitudeBrainSize} / ${T1wBrainSize}) < 0.75 ) {1}" | bc -l) = X1 ]] ; then
I don't think we edited that line.

2025-01-07 01:32 UTC, glasserm commented on fMRISurface/GenericfMRISurfaceProcessingPipeline.sh
> +    log_Warn "         HCP Pipelines as it results in poorer cross-session functional and cortical areal "
Agree

2025-01-07 01:35 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    cmd=(${RUN} ${PipelineScripts}/OneStepResampling.sh \
I think we should delete it if we don't need it.

2025-01-07 01:36 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"
You need to suppress white space changes and then it is not confusing.  I always forget to do that too.

2025-01-07 01:37 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +#Split echos.
You should not run this block in longitudinal mode, so please if/then it accordingly.

2025-01-07 01:37 UTC, glasserm commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ -n "$fMRIReference" ] && [ "$fMRIReference" != "NONE" ]; then
The fMRIReference code should not actually do anything in longitudinal mode if longitudinal mode is implemented correctly, so we don't need an error message here.  It is fine if people used fMRIReference in cross-sectional mode.

2025-01-07 01:38 UTC, glasserm commented on fMRIVolume/scripts/OneStepResampling.sh
>  opts_AddMandatory '--ojacobian' 'JacobianOut' 'image' "output transformed + distortion corrected Jacobian image"
I would prefer that they were deleted and just put in a separate commit/pull request to reduce the likelihood of confusion later.

2025-01-07 01:39 UTC, glasserm commented on fMRISurface/scripts/RibbonVolumeToSurfaceMapping.sh
> +Session="$3"
Agree, though perhaps not worth changing it back...

2025-01-07 01:41 UTC, glasserm commented
Since my attempt at e-mail-based comments didn't work, I deleted them and moved them to the appropriate threads.

2025-01-15 19:00 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +        log_Err_Abort "the --longitudinal-session must be specified and folder must exist in longitudinal mode"
Correct. But is-longitudinal option is standard way to point to longitudinal session across scripts, instead of forcing the user to guess it is not required here.

2025-01-15 20:27 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    if [ -n "$fMRIReference" ] && [ "$fMRIReference" != "NONE" ]; then
Changed to warning, adding Tim's suggested prompt.

2025-01-15 20:41 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"
With regards to the original @coalsont comment about _orig_, I don't recall modifying this line, but I just reverted it to the master branch version.

2025-01-15 20:57 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +#Split echos.
The block between lines (new) 683 and 809 is already only run in cross-sectional mode. Did you mean the next 'split echos' block? For that, I kept statements assigning [tcs/sct]Echoes[..] but put all wb_command commands under conditional.

2025-01-15 20:59 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +    cmd=(${RUN} ${PipelineScripts}/OneStepResampling.sh \
Ok

2025-01-15 21:01 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +        log_Err_Abort "--t1w-cross2long-xfm must point to a valid file when --is-longitudinal is used"
Same as above, trying to be consistent across longitudinal /cross-sectional parameters

2025-01-15 21:03 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +            #ScoutExtension="_undistorted" this is now initialized before case switch to accomodate longitudinal mode
ok

2025-01-15 21:13 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> -        cp "${WD}/${ScoutInputFile}${ScoutExtension}2T1w_init.mat" "${WD}/fMRI2str.mat"
Ok

2025-01-15 21:14 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +            ${FSLDIR}/bin/imcp ${fMRIReferencePath}/"${fMRIReference}_${simage}" ${fMRIFolder}/"${NameOffMRI}_${simage}"
It appears to have been part of the conflict section I marked in this commit:

d5a2fe43c2cdbcdd185314b428a1951914e99ee1

So, what probably happened is when I didn't try to resolve this while rebasing the commits to a fresh branch, you saw that you had already seen that code, and deleted the lines that included the (subtle, recent) change to add `_orig_` to those copies.

2025-01-15 21:17 UTC, mmilch01 commented on fMRIVolume/scripts/OneStepResampling.sh
>  opts_AddMandatory '--ojacobian' 'JacobianOut' 'image' "output transformed + distortion corrected Jacobian image"
Ok

2025-01-15 21:33 UTC, coalsont commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +esac
```suggestion
case $DistortionCorrection in
	${FIELDMAP_METHOD_OPT} | ${SIEMENS_METHOD_OPT} | ${GE_HEALTHCARE_LEGACY_METHOD_OPT} | ${GE_HEALTHCARE_METHOD_OPT} | ${PHILIPS_METHOD_OPT} | ${SPIN_ECHO_METHOD_OPT} )
		ScoutExtension="_undistorted" 
	;;
	${NONE_METHOD_OPT})
		ScoutExtension="_nosdc" 
	;;
esac
```
Hard to see the "do this" part when it is on the end of a long line.

2025-01-22 04:07 UTC, coalsont commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +#Split echos.
At the moment, it will still print "splitting echoes" if multi echo is detected, even though it only sets some shell variables.  If we don't need any of the variables in longitudinal mode, I would put the longitudinal conditional around the entire block instead of buried in the loop, for readability (and avoiding wrong messages).

2025-01-22 04:19 UTC, coalsont commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +                #ScoutExtension="_nosdc" #this is now initialized before case switch to accomodate longitudinal mode
We deleted the other lines like this instead of commenting them out.

2025-01-22 04:22 UTC, coalsont commented on fMRIVolume/scripts/OneStepResampling.sh
> +#verbose_echo "--freesruferbrainmask-native: $FreeSurferBrainMaskNative"
This looks like more native-space-output stuff.

2025-01-22 15:19 UTC, mmilch01 commented on fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
> +                #ScoutExtension="_nosdc" #this is now initialized before case switch to accomodate longitudinal mode
Ok

2025-01-22 15:20 UTC, mmilch01 commented on fMRIVolume/scripts/OneStepResampling.sh
> +#verbose_echo "--freesruferbrainmask-native: $FreeSurferBrainMaskNative"
Removed.

2025-01-22 15:30 UTC, mmilch01 commented on fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
> +#Split echos.
We do need tcsEchoes* to be set for multi-echo for both longitudinal and non-longitudinal modes. The if clause inside the "for iEcho.." loop prevents re-running wb_command in longitudinal mode.

2025-01-22 15:36 UTC, coalsont commented on fMRIVolume/scripts/OneStepResampling.sh
> +#T1wImageFileNative=$(basename $T1wImageNative)
This line also looks like a native volume space change, commented out.

2025-02-19 22:23 UTC, coalsont commented on PostFreeSurfer/PostFreeSurferPipelineLongPrep.sh
> +        mkdir -p $AtlasSpaceFolder_timepoint
With the rebase onto the fixes in master, this line is redundant.

2025-02-21 00:15 UTC, merged